### ISSUE TITLE
Staging cadvisor configuration/prometheus configuration

### ISSUE THREAD

**Issue by matusdrobuliak66** [ITISFoundation/osparc-ops-environments#354]
During the release to staging, we found out that the resource-usage-tracker is unable to start. https://github.com/ITISFoundation/osparc-simcore/issues/4744 

```
log_level=ERROR | log_timestamp=2023-09-14 14:56:24,006 | log_source=uvicorn.error:send(123) | log_uid=None | log_msg=Traceback (most recent call last):\n  File "/home/scu/.venv/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan\n    async with self.lifespan_context(app) as maybe_state:\n  File "/home/scu/.venv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__\n    await self._router.startup()\n  File "/home/scu/.venv/lib/python3.10/site-packages/starlette/routing.py", line 654, in startup\n    await handler()\n  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_resource_usage_tracker/modules/prometheus.py", line 59, in on_startup\n    app.state.prometheus_api_client = await create_client(settings)\n  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_resource_usage_tracker/modules/prometheus.py", line 43, in create_client\n    raise ConfigurationError(\nsimcore_service_resource_usage_tracker.core.errors.ConfigurationError: Application misconfiguration: Prometheus API client could be reached but returned value is not expected. TIP: check configuration\n
log_level=ERROR | log_timestamp=2023-09-14 14:56:24,007 | log_source=uvicorn.error:startup(59) | log_uid=None | log_msg=Application startup failed. Exiting.
```

when I go to `https://monitoring.osparc-staging.io/prometheuscadvisor/graph` I am not able to query some basic "container" metrics, I think as we didn't use it before in staging, maybe we didn't configure it there. 

NOTE: it would be nice to fix this, but I can also set in the resource tracker service that it should ignore the Prometheus connection as currently it is not used (but it will be in the future)

**Comment by mrnicegyu11** [comment]
as agreed with @matusdrobuliak66 we (for now) dont run the cadvisor-prometheus
